### ISSUE TITLE
Text tends to be duplicated

### ISSUE THREAD

**Issue by Tadaboody** [tht13/RST-vscode#10]
![image](https://user-images.githubusercontent.com/6463334/46937781-c846e400-d06a-11e8-9178-ecee90c4bad8.png)

Only happens to the text added between previews

- Extension Version: 3.0.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.1

**Comment by tht13** [comment]
Hi, could you provide a snippet of the offending text? and I will try to find the issue.
Thanks for reporting

**Comment by tht13** [comment]
Fixed in version 3.0.1
