### ISSUE TITLE
Preview failed on Unicode

### ISSUE THREAD

**Issue by lextm** [tht13/RST-vscode#3]
Also tracked as https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/8

Proposed a fix by forcing HTML pages to UTF-8.

**Comment by tht13** [comment]
I cannot view your tracked issue as it is private. 

I have encountered this issue before, I think using repr() could solve this issue and print it back to command line as a  bytestring.

**Comment by lextm** [comment]
Updated the link. The repo has been moved to an organization account, which you have been invited.

**Comment by lextm** [comment]
I just published a new build 0.0.9 of vscode-restructuredtext. Instead of using docutils, this build directly uses the sphinx generated HTML page, which is more accurate with theming and images.

**Comment by tht13** [comment]
Thanks for the update :smile: 
My only concern about using the generated sphinx files is that you cannot have instant preview as you type. It could be possible to take the sphinx generated material and then try to layer the docutils generated on top of it. Try to get the best of both worlds. Thoughts?

**Comment by lextm** [comment]
@tht13 sphinx-autobuild is a feasible option for instant preview. I am just wondering how I can use that smartly, so still investigate on that side. Rough idea is as below,

1. The user presses the shortcut to trigger preview.
1. The RST extension checks if sphinx-autobuild is running for the `conf.py`. It starts sphinx-autobuild automatically if needed.
1. The RST then goes to the generated HTML page and loads it in VS Code.

One biggest challenge comes from node.js side, as it lacks of a cross platform module to handle external processes.

**Comment by tht13** [comment]
This would work for small projects, but I regularly work with projects which take minutes to compile. Unless sphinx has added a way to just rebuild a single page. I'm aware you can add 'sub' conf.py files so you can build sub sections but ideally we shouldn't require the user to modify their project just for the extension.

Why would child_process not work? I use it in my other project `gerrit_vscode` and implement it in a very similar way to how vscode does itself. If you want to have a look it's in `src/common/exec.ts`

**Comment by lextm** [comment]
Just published 0.0.11 of vscode-restructuredtext, which contains two new settings to locate generated HTML pages,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md

I think if sphinx-autobuild is used now, you can set the `builtDocumentationPath` setting to point to the directory where sphinx-autobuild generates HTML pages. Then the preview should work whenever a change is made.

I did not have time to test that fully, but it seems to partially work. The current problem is that file change notification is not yet processed properly by vscode-restructuredtext, that the below method is called, but does not update the preview page,

https://github.com/tht13/RST-vscode/blob/master/src/extension.ts#L80

**Comment by tritium21** [comment]
I have corrected encoding, at least in my testing in #4

**Comment by tht13** [comment]
Issue should be fixed in [v1.3.0](https://github.com/tht13/RST-vscode/releases/tag/v1.3.0)
Please reopen if further encoding issues are found.
Thank you @tritium21 for PR #4
