### ISSUE TITLE
not support :kbd:`Enter`

### ISSUE THREAD

**Issue by fenbox** [tht13/RST-vscode#5]
## not support

```
:kbd:`Enter`
```

error msg:

![image](https://cloud.githubusercontent.com/assets/360618/15800865/1551e002-2ab8-11e6-8973-97f0b846ebb4.png)

## other

- Can't Toggle Preview, only can preview but can't back to edit with `ctrl+shift+r`.
- Can't click link in preview

**Comment by tht13** [comment]
The `kdb` tag is a [Sphinx specific tag](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-kbd) which is a superset of RST. This extension only supports tags defined in the [docutils python module](http://docutils.sourceforge.net/docs/user/rst/quickref.html).

As for the other two issues, the first is being worked on but is dependent on the VSCode team opening up some more features of the API, the second I would classify as a `nice to have` but will look into :smile:

**Comment by lextm** [comment]
@tht13 an update from Microsoft is that Markdown becomes an individual extension (instead of hooking deeply with VSCode itself), so that opening up the opportunities for the two reStructuredText extensions.

**Comment by tht13** [comment]
@lextm I have been tracking this issue as it is also functionality I will incorporate into my html preview extension :smile: 
I have raised [this issue](https://github.com/Microsoft/vscode/issues/6941) for VSCode as a suggestiong for how this can be done, both for our extensions and their markdown one.
